version: '3'

services:
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/first_project
    ports:
      - '8000:8000'
    networks:
      - app
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.0.29
    ports:
      - '3309:3306'
    environment:
      MYSQL_DATABASE: 'first_project'
      MYSQL_ROOT: 'root'
      MYSQL_ROOT_PASSWORD: 'SQListhebest'
    restart: always
    networks:
      - app

networks:
  app:
    driver: bridge